---

- name: Apt install bc
  ansible.builtin.apt:
    name: bc
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Copy over plugins
  ansible.builtin.copy:
    src: munin-bitcoin/{{ item }}
    dest: /usr/share/munin/plugins/{{ item }}
    mode: a+x
  with_items:
    - bitcoind_blockchain_size
    - bitcoind_blockchain_verification
    - bitcoind_blocks
    - bitcoind_connections
    - bitcoind_difficulty
    - bitcoind_mempool_bytes
    - bitcoind_mempool_size
    - bitcoind_network_traffic
  become: true
  notify: Bitcoin_restart_munin_node

- name: Enable unbound_munin_histogram
  ansible.builtin.file:
    src: /usr/share/munin/plugins/{{ item }}
    dest: /etc/munin/plugins/{{ item }}
    state: link
  with_items:
    - bitcoind_blockchain_size
    - bitcoind_blockchain_verification
    - bitcoind_blocks
    - bitcoind_connections
    - bitcoind_difficulty
    - bitcoind_mempool_bytes
    - bitcoind_mempool_size
    - bitcoind_network_traffic
  become: true
  notify: Bitcoin_restart_munin_node

- name: Add munin plugin-conf
  ansible.builtin.template:
    src: munin-plugin.conf
    dest: /etc/munin/plugin-conf.d/bitcoind
    mode: '0644'
  become: true
  notify: Bitcoin_restart_munin_node
