---

- name: Create bitcoin user
  ansible.builtin.user:
    name: "{{ bitcoin_user }}"
    shell: /usr/sbin/nologin
    home: "{{ bitcoin_home }}"
    system: true
  become: true
  when: bitcoin_user != 'root'

- name: Make sure datadir/home exists
  ansible.builtin.file:
    path: "{{ bitcoin_home }}"
    state: directory
    mode: '0755'
  become: true
  when: bitcoin_user == 'root'

- name: Add bitcoind.service
  ansible.builtin.template:
    src: bitcoind.service.ini
    dest: /lib/systemd/system/bitcoind.service
    mode: '0644'
  become: true
  notify:
    - Bitcoin_reload_systemd
    - Restart_bitcoind

- name: Create folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
    owner: "{{ bitcoin_user }}"
  with_items:
    - "{{ bitcoin_conf_pid | dirname }}"
    - /etc/bitcoin
  become: true

- name: Add bitcoind.conf
  ansible.builtin.template:
    src: bitcoind.conf
    dest: /etc/bitcoin/bitcoind.conf
    mode: '0640'
  become: true
  become_user: "{{ bitcoin_user }}"
  notify: Restart_bitcoind
