---

- name: create bitcoin user
  user:
    name: "{{ bitcoin_user }}"
    shell: /usr/sbin/nologin
    home: "{{ bitcoin_home }}"
    system: yes
  become: yes
  when: bitcoin_user != 'root'

- name: make sure datadir/home exists
  file:
    path: "{{ bitcoin_home }}"
    state: directory
    mode: 0755
  become: yes
  when: bitcoin_user == 'root'

- name: add bitcoind.service
  template:
    src: bitcoind.service.ini
    dest: /lib/systemd/system/bitcoind.service
    mode: 0644
  become: yes
  notify:
    - bitcoin_reload_systemd
    - restart_bitcoind

- name: create folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ bitcoin_user }}"
  with_items:
    - "{{ bitcoin_conf_pid | dirname }}"
    - /etc/bitcoin
  become: yes

- name: add bitcoind.conf
  template:
    src: bitcoind.conf
    dest: /etc/bitcoin/bitcoind.conf
    mode: 0640
  become: yes
  become_user: "{{ bitcoin_user }}"
  notify: restart_bitcoind
