version: 2.1

jobs:

  build:
    machine:
      image: ubuntu-2004:202104-01
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: pip3 install ansible
      - run: ansible --version

      - checkout
      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run:
          command: ansible-playbook tests/test.yml -i tests/inventory --connection=local
          no_output_timeout: 20m
      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local
      - run: bitcoin-cli -version
      - run: sudo cat /etc/bitcoin/bitcoind.conf
      - run: sudo systemctl stop bitcoind
