---

- name: Reload systemd
  listen: bitcoin_reload_systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart munin-node
  listen: bitcoin_restart_munin_node
  ansible.builtin.systemd_service:
    name: munin-node
    state: restarted
  become: true

- name: Restart bitcoind
  listen: bitcoin_restart_bitcoind
  ansible.builtin.systemd_service:
    name: bitcoind
    state: restarted
    enabled: true
  become: true
