---

- name: Bitcoin_reload_systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Bitcoin_restart_munin_node
  ansible.builtin.systemd:
    name: munin-node
    state: restarted
  become: true

- name: Restart_bitcoind
  ansible.builtin.systemd:
    name: bitcoind
    state: restarted
    enabled: true
  become: true
