---

- name: bitcoin_reload_systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: bitcoin_restart_munin_node
  ansible.builtin.systemd:
    name: munin-node
    state: restarted
  become: yes

- name: restart_bitcoind
  ansible.builtin.systemd:
    name: bitcoind
    state: restarted
    enabled: yes
  become: yes
