# {{ ansible_managed }}

[Unit]
Description=Bitcoins distributed currency daemon
After=network.target

[Service]
User={{ bitcoin_user }}

Type=forking
ExecStart=/usr/local/bin/bitcoind -daemon -conf=/etc/bitcoin/bitcoind.conf
{% if bitcoin_conf_pid is defined %}
PIDFile={{ bitcoin_conf_pid }}
{% endif %}

Restart=always
PrivateTmp=true

TimeoutStopSec=10m
TimeoutStartSec=10m

[Install]
WantedBy=multi-user.target
